---
- name: Copy Release Tar file from Local Server to Remote Server
  hosts: linux

  tasks:
    - name: Copying file
      copy:
        src: release.tar.gz
        dest: /tmp/
        remote_src: yes
...
